# Base image
FROM node:18.16-alpine

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package.json ./

# Install dependencies
RUN yarn install

# Copy the source code
COPY . .
